name: simplerag-stack
services:

  python3:
    image: simplerag:0.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/workspace
    container_name: simplerag-app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # https://github.com/Unstructured-IO/unstructured-api
  unstructured:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:latest
    container_name: simplerag-unstructured
    restart: always
    ports:
      - 8051:8000
    environment:
      - UNSTRUCTURED_API_KEY="unstructured"
